### ISSUE TITLE
ReferenceError: BigInt is not defined

### ISSUE THREAD

**Issue by SaubereSache** [dollarshaveclub/cloudworker#114]
Hello,
when I try to use Cloudworker on any valid Cloudflare Worker file, it shows me this stacktrace (OS: Windows 10 x64).
As I already searched online and haven't found anything I'm posting this issue to (hopefully) find a solution.

`C:\Users\Constantin Schreiber\WebstormProjects\workertsc\dist>cloudworker worker.js
Starting up...
ReferenceError: BigInt is not defined
    at new Context (C:\Users\Constantin Schreiber\AppData\Roaming\npm\node_modules\@dollarshaveclub\cloudworker\lib\runtime.js:37:19)
    at new Cloudworker (C:\Users\Constantin Schreiber\AppData\Roaming\npm\node_modules\@dollarshaveclub\cloudworker\lib\cloudworker.js:25:20)
    at run (C:\Users\Constantin Schreiber\AppData\Roaming\npm\node_modules\@dollarshaveclub\cloudworker\bin\cloudworker.js:54:16)
    at wasmLoader.loadBindings.then.res (C:\Users\Constantin Schreiber\AppData\Roaming\npm\node_modules\@dollarshaveclub\cloudworker\bin\cloudworker.js:37:3)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3`

**Comment by svemir** [comment]
I had the same problem, but I am not 100% sure what was the solution. I think I fixed it by updating from node v8 to v10.

**Comment by SaubereSache** [comment]
Needed to uninstall my old Node (v8) and delete all global NPM modules (located at %appdata%\npm in Windows) and reinstall Node v10 and Cloudworker.
